### ISSUE TITLE
Overwrites updatetime if not set to default value

### ISSUE THREAD

**Issue by willwillsiii** [PhilRunninger/nerdtree-buffer-ops#3]
This plugin overrides the value of `updatetime` through an autocommand, which can interfere with other plugins.

https://github.com/PhilRunninger/nerdtree-buffer-ops/blob/bd0cd6bd6db38d1641d24fc5d4c65e066eb0781b/nerdtree_plugin/highlight_open_buffers.vim#L25-L30

If `updatetime` must be set, then perhaps consider storing its initial value and resetting to that instead.

**Comment by PhilRunninger** [comment]
What happens if all mentions of the `'updatetime'` setting are removed? It's probably not that important to have an immediate response.

**Comment by willwillsiii** [comment]
The highlighting of active buffers is slower to update. It's noteworthy that it seems to automatically update when interacting with files through nerdtree. The highlight only lags behind in my testing when a buffer is wiped, and even then nerdtree reflects this change after `updatetime` milliseconds (default 4 seconds).

I'm inclined to agree that perhaps it's not necessary.
