### ISSUE TITLE
perf problem

### ISSUE THREAD

**Issue by jinleileiking** [PhilRunninger/nerdtree-buffer-ops#5]
https://github.com/preservim/nerdtree/issues/1357

**Comment by PhilRunninger** [comment]
This is a problem with the design of NERDTree. When it is used on a large directory, it just consumes way too many resources by acting as a object-oriented language. Combine that with Vimscript's being slow and interpreted, and you end up with a miserable experience. **nerdtree-buffer-ops** is already as efficient as it's ever going to get.
